/**
 * @Auth Types
 */

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


/**
 * Product Types
 */
 export const PRODUCT_FETCHING_START   = 'START_FETCHING_PRODUCT';
 export const PRODUCT_FETCHED_DONE     = 'PRODUCT_FETCHED_DONE';
 export const PRODUCT_FETCHING_FAILED  = 'PRODUCT_FETCHING_FAILED';
 export const QUANTITY_UPDATE_START  = 'QUANTITY_UPDATE_START';

 export const QUANTITY_INCREMENT  = 'QUANTITY_INCREMENT';
 export const QUANTITY_DECREMENT  = 'QUANTITY_DECREMENT';
 
 export const QUANTITY_UPDATE_FAILED  = 'PRODUCT_UPDATE_FAILED';

 
 /**
  * Cart Types
  * 
  */
 
 export const INITIALIZE_ADD_PRODUCT_TO_CART = 'INITIALIZE_ADD_PRODUCT_TO_CART';
 export const PRODUCT_ADDED_IN_CART = 'PRODUCT_ADDED_IN_CART';
 export const FAILED_TO_ADD_PRODUCT_IN_CART = 'FAILED_TO_ADD_PRODUCT_IN_CART';



export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';